// @routes-hash d482a1b197a774825d3bc1c4ca8b70c5
import { Express } from "express";

import route1 from "./routes/agents/clearMemory";
import route2 from "./routes/agents/getMemory";
import route3 from "./routes/artStyle/getArtStyle";
import route4 from "./routes/assets/addAssets";
import route5 from "./routes/assets/batchDelete";
import route6 from "./routes/assets/batchGenerationData";
import route7 from "./routes/assets/delAssets";
import route8 from "./routes/assets/getAssetsApi";
import route9 from "./routes/assets/getImage";
import route10 from "./routes/assets/saveAssets";
import route11 from "./routes/assets/updateAssets";
import route12 from "./routes/assets/uploadClip";
import route13 from "./routes/assetsGenerate/generateAssets";
import route14 from "./routes/assetsGenerate/polishAssetsPrompt";
import route15 from "./routes/cornerScape/getAllAssets";
import route16 from "./routes/general/generalStatistics";
import route17 from "./routes/general/getSingleProject";
import route18 from "./routes/general/updateProject";
import route19 from "./routes/login/login";
import route20 from "./routes/migrate/migrateData";
import route21 from "./routes/modelSelect/getModelDetail";
import route22 from "./routes/modelSelect/getModelList";
import route23 from "./routes/novel/addNovel";
import route24 from "./routes/novel/batchDeleteNovel";
import route25 from "./routes/novel/delNovel";
import route26 from "./routes/novel/event/batchDeleteEvent";
import route27 from "./routes/novel/event/deletEvent";
import route28 from "./routes/novel/event/generateEvents";
import route29 from "./routes/novel/event/getEvent";
import route30 from "./routes/novel/getNovel";
import route31 from "./routes/novel/getNovelEventState";
import route32 from "./routes/novel/getNovelIndex";
import route33 from "./routes/novel/updateNovel";
import route34 from "./routes/other/deleteAllData";
import route35 from "./routes/other/getCaptcha";
import route36 from "./routes/production/assets/getAssetsData";
import route37 from "./routes/production/editStoryboard/generateStoryboardImage";
import route38 from "./routes/production/editStoryboard/getStoryboardFlow";
import route39 from "./routes/production/editStoryboard/saveStoryboardFlow";
import route40 from "./routes/production/editStoryboard/updateStoryboardFlow";
import route41 from "./routes/production/exportImage";
import route42 from "./routes/production/getFlowData";
import route43 from "./routes/production/getProductionData";
import route44 from "./routes/production/getStoryboardData";
import route45 from "./routes/production/saveFlowData";
import route46 from "./routes/production/workbench/confirmSelection";
import route47 from "./routes/production/workbench/delVideo";
import route48 from "./routes/production/workbench/generateVideo";
import route49 from "./routes/production/workbench/getChatLines";
import route50 from "./routes/production/workbench/getVideoModelDetail";
import route51 from "./routes/production/workbench/videoPolling";
import route52 from "./routes/project/addProject";
import route53 from "./routes/project/delProject";
import route54 from "./routes/project/editProject";
import route55 from "./routes/project/getProject";
import route56 from "./routes/script/addScript";
import route57 from "./routes/script/delScript";
import route58 from "./routes/script/exportScript";
import route59 from "./routes/script/getScrptApi";
import route60 from "./routes/script/updateScript";
import route61 from "./routes/scriptAgent/getPlanData";
import route62 from "./routes/scriptAgent/setPlanData";
import route63 from "./routes/setting/agentDeploy/deployAgentModel";
import route64 from "./routes/setting/agentDeploy/getAgentDeploy";
import route65 from "./routes/setting/agentDeploy/updateKey";
import route66 from "./routes/setting/dbConfig/clearData";
import route67 from "./routes/setting/getTextModel";
import route68 from "./routes/setting/loginConfig/getUser";
import route69 from "./routes/setting/loginConfig/updateUserPwd";
import route70 from "./routes/setting/memoryConfig/getMemory";
import route71 from "./routes/setting/memoryConfig/sureMemory";
import route72 from "./routes/setting/vendorConfig/addVendor";
import route73 from "./routes/setting/vendorConfig/deleteVendor";
import route74 from "./routes/setting/vendorConfig/getVendorList";
import route75 from "./routes/setting/vendorConfig/modelTest";
import route76 from "./routes/setting/vendorConfig/updateVendor";
import route77 from "./routes/task/getTaskApi";
import route78 from "./routes/task/getTaskCategories";
import route79 from "./routes/task/taskDetails";
import route80 from "./routes/test/test";

export default async (app: Express) => {
  app.use("/api/agents/clearMemory", route1);
  app.use("/api/agents/getMemory", route2);
  app.use("/api/artStyle/getArtStyle", route3);
  app.use("/api/assets/addAssets", route4);
  app.use("/api/assets/batchDelete", route5);
  app.use("/api/assets/batchGenerationData", route6);
  app.use("/api/assets/delAssets", route7);
  app.use("/api/assets/getAssetsApi", route8);
  app.use("/api/assets/getImage", route9);
  app.use("/api/assets/saveAssets", route10);
  app.use("/api/assets/updateAssets", route11);
  app.use("/api/assets/uploadClip", route12);
  app.use("/api/assetsGenerate/generateAssets", route13);
  app.use("/api/assetsGenerate/polishAssetsPrompt", route14);
  app.use("/api/cornerScape/getAllAssets", route15);
  app.use("/api/general/generalStatistics", route16);
  app.use("/api/general/getSingleProject", route17);
  app.use("/api/general/updateProject", route18);
  app.use("/api/login/login", route19);
  app.use("/api/migrate/migrateData", route20);
  app.use("/api/modelSelect/getModelDetail", route21);
  app.use("/api/modelSelect/getModelList", route22);
  app.use("/api/novel/addNovel", route23);
  app.use("/api/novel/batchDeleteNovel", route24);
  app.use("/api/novel/delNovel", route25);
  app.use("/api/novel/event/batchDeleteEvent", route26);
  app.use("/api/novel/event/deletEvent", route27);
  app.use("/api/novel/event/generateEvents", route28);
  app.use("/api/novel/event/getEvent", route29);
  app.use("/api/novel/getNovel", route30);
  app.use("/api/novel/getNovelEventState", route31);
  app.use("/api/novel/getNovelIndex", route32);
  app.use("/api/novel/updateNovel", route33);
  app.use("/api/other/deleteAllData", route34);
  app.use("/api/other/getCaptcha", route35);
  app.use("/api/production/assets/getAssetsData", route36);
  app.use("/api/production/editStoryboard/generateStoryboardImage", route37);
  app.use("/api/production/editStoryboard/getStoryboardFlow", route38);
  app.use("/api/production/editStoryboard/saveStoryboardFlow", route39);
  app.use("/api/production/editStoryboard/updateStoryboardFlow", route40);
  app.use("/api/production/exportImage", route41);
  app.use("/api/production/getFlowData", route42);
  app.use("/api/production/getProductionData", route43);
  app.use("/api/production/getStoryboardData", route44);
  app.use("/api/production/saveFlowData", route45);
  app.use("/api/production/workbench/confirmSelection", route46);
  app.use("/api/production/workbench/delVideo", route47);
  app.use("/api/production/workbench/generateVideo", route48);
  app.use("/api/production/workbench/getChatLines", route49);
  app.use("/api/production/workbench/getVideoModelDetail", route50);
  app.use("/api/production/workbench/videoPolling", route51);
  app.use("/api/project/addProject", route52);
  app.use("/api/project/delProject", route53);
  app.use("/api/project/editProject", route54);
  app.use("/api/project/getProject", route55);
  app.use("/api/script/addScript", route56);
  app.use("/api/script/delScript", route57);
  app.use("/api/script/exportScript", route58);
  app.use("/api/script/getScrptApi", route59);
  app.use("/api/script/updateScript", route60);
  app.use("/api/scriptAgent/getPlanData", route61);
  app.use("/api/scriptAgent/setPlanData", route62);
  app.use("/api/setting/agentDeploy/deployAgentModel", route63);
  app.use("/api/setting/agentDeploy/getAgentDeploy", route64);
  app.use("/api/setting/agentDeploy/updateKey", route65);
  app.use("/api/setting/dbConfig/clearData", route66);
  app.use("/api/setting/getTextModel", route67);
  app.use("/api/setting/loginConfig/getUser", route68);
  app.use("/api/setting/loginConfig/updateUserPwd", route69);
  app.use("/api/setting/memoryConfig/getMemory", route70);
  app.use("/api/setting/memoryConfig/sureMemory", route71);
  app.use("/api/setting/vendorConfig/addVendor", route72);
  app.use("/api/setting/vendorConfig/deleteVendor", route73);
  app.use("/api/setting/vendorConfig/getVendorList", route74);
  app.use("/api/setting/vendorConfig/modelTest", route75);
  app.use("/api/setting/vendorConfig/updateVendor", route76);
  app.use("/api/task/getTaskApi", route77);
  app.use("/api/task/getTaskCategories", route78);
  app.use("/api/task/taskDetails", route79);
  app.use("/api/test/test", route80);
}
