// @routes-hash 3aef51df31467bb6ff0ed05b9520c86e
import { Express } from "express";

import route1 from "./routes/agents/clearMemory";
import route2 from "./routes/agents/getMemory";
import route3 from "./routes/agents/productionAgent";
import route4 from "./routes/artStyle/getArtStyle";
import route5 from "./routes/assets/addAssets";
import route6 from "./routes/assets/batchDelete";
import route7 from "./routes/assets/batchGenerationData";
import route8 from "./routes/assets/delAssets";
import route9 from "./routes/assets/getAssetsApi";
import route10 from "./routes/assets/getImage";
import route11 from "./routes/assets/saveAssets";
import route12 from "./routes/assets/updateAssets";
import route13 from "./routes/assets/uploadClip";
import route14 from "./routes/assetsGenerate/generateAssets";
import route15 from "./routes/assetsGenerate/polishAssetsPrompt";
import route16 from "./routes/cornerScape/getAllAssets";
import route17 from "./routes/general/generalStatistics";
import route18 from "./routes/general/getSingleProject";
import route19 from "./routes/general/updateProject";
import route20 from "./routes/login/login";
import route21 from "./routes/migrate/migrateData";
import route22 from "./routes/modelSelect/getModelList";
import route23 from "./routes/novel/addNovel";
import route24 from "./routes/novel/batchDeleteNovel";
import route25 from "./routes/novel/delNovel";
import route26 from "./routes/novel/event/batchDeleteEvent";
import route27 from "./routes/novel/event/deletEvent";
import route28 from "./routes/novel/event/generateEvents";
import route29 from "./routes/novel/event/getEvent";
import route30 from "./routes/novel/getNovel";
import route31 from "./routes/novel/updateNovel";
import route32 from "./routes/other/deleteAllData";
import route33 from "./routes/other/getCaptcha";
import route34 from "./routes/production/getProductionData";
import route35 from "./routes/project/addProject";
import route36 from "./routes/project/delProject";
import route37 from "./routes/project/editProject";
import route38 from "./routes/project/getProject";
import route39 from "./routes/script/addScript";
import route40 from "./routes/script/delScript";
import route41 from "./routes/script/getScrptApi";
import route42 from "./routes/script/updateScript";
import route43 from "./routes/setting/agentDeploy/deployAgentModel";
import route44 from "./routes/setting/agentDeploy/getAgentDeploy";
import route45 from "./routes/setting/agentDeploy/updateKey";
import route46 from "./routes/setting/dbConfig/clearData";
import route47 from "./routes/setting/getTextModel";
import route48 from "./routes/setting/loginConfig/getUser";
import route49 from "./routes/setting/loginConfig/updateUserPwd";
import route50 from "./routes/setting/memoryConfig/getMemory";
import route51 from "./routes/setting/memoryConfig/sureMemory";
import route52 from "./routes/setting/vendorConfig/addVendor";
import route53 from "./routes/setting/vendorConfig/deleteVendor";
import route54 from "./routes/setting/vendorConfig/getVendorList";
import route55 from "./routes/setting/vendorConfig/modelTest";
import route56 from "./routes/setting/vendorConfig/updateVendor";
import route57 from "./routes/task/getMyTaskApi";
import route58 from "./routes/task/getTaskCategories";
import route59 from "./routes/task/taskDetails";
import route60 from "./routes/test/test";

export default async (app: Express) => {
  app.use("/api/agents/clearMemory", route1);
  app.use("/api/agents/getMemory", route2);
  app.use("/api/agents/productionAgent", route3);
  app.use("/api/artStyle/getArtStyle", route4);
  app.use("/api/assets/addAssets", route5);
  app.use("/api/assets/batchDelete", route6);
  app.use("/api/assets/batchGenerationData", route7);
  app.use("/api/assets/delAssets", route8);
  app.use("/api/assets/getAssetsApi", route9);
  app.use("/api/assets/getImage", route10);
  app.use("/api/assets/saveAssets", route11);
  app.use("/api/assets/updateAssets", route12);
  app.use("/api/assets/uploadClip", route13);
  app.use("/api/assetsGenerate/generateAssets", route14);
  app.use("/api/assetsGenerate/polishAssetsPrompt", route15);
  app.use("/api/cornerScape/getAllAssets", route16);
  app.use("/api/general/generalStatistics", route17);
  app.use("/api/general/getSingleProject", route18);
  app.use("/api/general/updateProject", route19);
  app.use("/api/login/login", route20);
  app.use("/api/migrate/migrateData", route21);
  app.use("/api/modelSelect/getModelList", route22);
  app.use("/api/novel/addNovel", route23);
  app.use("/api/novel/batchDeleteNovel", route24);
  app.use("/api/novel/delNovel", route25);
  app.use("/api/novel/event/batchDeleteEvent", route26);
  app.use("/api/novel/event/deletEvent", route27);
  app.use("/api/novel/event/generateEvents", route28);
  app.use("/api/novel/event/getEvent", route29);
  app.use("/api/novel/getNovel", route30);
  app.use("/api/novel/updateNovel", route31);
  app.use("/api/other/deleteAllData", route32);
  app.use("/api/other/getCaptcha", route33);
  app.use("/api/production/getProductionData", route34);
  app.use("/api/project/addProject", route35);
  app.use("/api/project/delProject", route36);
  app.use("/api/project/editProject", route37);
  app.use("/api/project/getProject", route38);
  app.use("/api/script/addScript", route39);
  app.use("/api/script/delScript", route40);
  app.use("/api/script/getScrptApi", route41);
  app.use("/api/script/updateScript", route42);
  app.use("/api/setting/agentDeploy/deployAgentModel", route43);
  app.use("/api/setting/agentDeploy/getAgentDeploy", route44);
  app.use("/api/setting/agentDeploy/updateKey", route45);
  app.use("/api/setting/dbConfig/clearData", route46);
  app.use("/api/setting/getTextModel", route47);
  app.use("/api/setting/loginConfig/getUser", route48);
  app.use("/api/setting/loginConfig/updateUserPwd", route49);
  app.use("/api/setting/memoryConfig/getMemory", route50);
  app.use("/api/setting/memoryConfig/sureMemory", route51);
  app.use("/api/setting/vendorConfig/addVendor", route52);
  app.use("/api/setting/vendorConfig/deleteVendor", route53);
  app.use("/api/setting/vendorConfig/getVendorList", route54);
  app.use("/api/setting/vendorConfig/modelTest", route55);
  app.use("/api/setting/vendorConfig/updateVendor", route56);
  app.use("/api/task/getMyTaskApi", route57);
  app.use("/api/task/getTaskCategories", route58);
  app.use("/api/task/taskDetails", route59);
  app.use("/api/test/test", route60);
}
